/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRandomNumberGeneratorInterface extends ethers.utils.Interface {
  functions: {
    "expand(uint256,uint256)": FunctionFragment;
    "getRandomNumber(uint256)": FunctionFragment;
    "getRandomResult()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "expand",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomResult",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "expand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomResult",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRandomNumberGenerator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRandomNumberGeneratorInterface;

  functions: {
    expand(
      randomValue: BigNumberish,
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { expandedValues: BigNumber[] }>;

    getRandomNumber(
      userProvidedSeed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getRandomResult(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  expand(
    randomValue: BigNumberish,
    n: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getRandomNumber(
    userProvidedSeed: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getRandomResult(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    expand(
      randomValue: BigNumberish,
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getRandomNumber(
      userProvidedSeed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRandomResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    expand(
      randomValue: BigNumberish,
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRandomNumber(
      userProvidedSeed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getRandomResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    expand(
      randomValue: BigNumberish,
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRandomNumber(
      userProvidedSeed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getRandomResult(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
