/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MockVRFCoordinatorInterface extends ethers.utils.Interface {
  functions: {
    "LINK()": FunctionFragment;
    "callBackWithRandomness(bytes32,uint256,address)": FunctionFragment;
    "currentLotteryId()": FunctionFragment;
    "onTokenTransfer(address,uint256,bytes)": FunctionFragment;
    "randomResult()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "LINK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "callBackWithRandomness",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "currentLotteryId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "randomResult",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "LINK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callBackWithRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLotteryId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomResult",
    data: BytesLike
  ): Result;

  events: {
    "RandomnessRequest(address,bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RandomnessRequest"): EventFragment;
}

export type RandomnessRequestEvent = TypedEvent<
  [string, string, BigNumber] & {
    sender: string;
    keyHash: string;
    seed: BigNumber;
  }
>;

export class MockVRFCoordinator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockVRFCoordinatorInterface;

  functions: {
    LINK(overrides?: CallOverrides): Promise<[string]>;

    callBackWithRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      consumerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    currentLotteryId(overrides?: CallOverrides): Promise<[BigNumber]>;

    onTokenTransfer(
      sender: string,
      fee: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    randomResult(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  LINK(overrides?: CallOverrides): Promise<string>;

  callBackWithRandomness(
    requestId: BytesLike,
    randomness: BigNumberish,
    consumerContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

  onTokenTransfer(
    sender: string,
    fee: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  randomResult(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    LINK(overrides?: CallOverrides): Promise<string>;

    callBackWithRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      consumerContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      sender: string,
      fee: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    randomResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "RandomnessRequest(address,bytes32,uint256)"(
      sender?: string | null,
      keyHash?: BytesLike | null,
      seed?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { sender: string; keyHash: string; seed: BigNumber }
    >;

    RandomnessRequest(
      sender?: string | null,
      keyHash?: BytesLike | null,
      seed?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { sender: string; keyHash: string; seed: BigNumber }
    >;
  };

  estimateGas: {
    LINK(overrides?: CallOverrides): Promise<BigNumber>;

    callBackWithRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      consumerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    currentLotteryId(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      sender: string,
      fee: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    randomResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    LINK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    callBackWithRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      consumerContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    currentLotteryId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onTokenTransfer(
      sender: string,
      fee: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    randomResult(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
