/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomNumberGenerator,
  IRandomNumberGeneratorInterface,
} from "../IRandomNumberGenerator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "randomValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "n",
        type: "uint256",
      },
    ],
    name: "expand",
    outputs: [
      {
        internalType: "uint256[]",
        name: "expandedValues",
        type: "uint256[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "userProvidedSeed",
        type: "uint256",
      },
    ],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getRandomResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRandomNumberGenerator__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomNumberGeneratorInterface {
    return new utils.Interface(_abi) as IRandomNumberGeneratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomNumberGenerator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRandomNumberGenerator;
  }
}
